---
deployment:
  tasks:
    - export DEPLOYPATH=/home/t49403/public_html/ufeapp/
    - /bin/cp admin/index.php $DEPLOYPATH
    - /bin/cp admin/block_need_confirm.php $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH